package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class claimData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "claimRefrenceNumber")
	private java.lang.String claimRefrenceNumber;

	public claimData() {
	}

	public java.lang.String getClaimRefrenceNumber() {
		return this.claimRefrenceNumber;
	}

	public void setClaimRefrenceNumber(java.lang.String claimRefrenceNumber) {
		this.claimRefrenceNumber = claimRefrenceNumber;
	}

	public claimData(java.lang.String claimRefrenceNumber) {
		this.claimRefrenceNumber = claimRefrenceNumber;
	}

}