package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class claimsObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNumber")
	private java.lang.String policyNumber;
	@org.kie.api.definition.type.Label("claimNumber")
	private java.lang.String claimNumber;

	@org.kie.api.definition.type.Label("processInstanceId")
	private java.lang.String processInstanceId;

	@org.kie.api.definition.type.Label("claimType")
	private java.lang.String claimType;

	@org.kie.api.definition.type.Label(value = "sa_ID")
	private java.lang.String sa_ID;

	public claimsObject() {
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public java.lang.String getClaimNumber() {
		return this.claimNumber;
	}

	public void setClaimNumber(java.lang.String claimNumber) {
		this.claimNumber = claimNumber;
	}

	public java.lang.String getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(java.lang.String claimType) {
		this.claimType = claimType;
	}

	public java.lang.String getSa_ID() {
		return this.sa_ID;
	}

	public void setSa_ID(java.lang.String sa_ID) {
		this.sa_ID = sa_ID;
	}

	public claimsObject(java.lang.String policyNumber,
			java.lang.String claimNumber, java.lang.String processInstanceId,
			java.lang.String claimType, java.lang.String sa_ID) {
		this.policyNumber = policyNumber;
		this.claimNumber = claimNumber;
		this.processInstanceId = processInstanceId;
		this.claimType = claimType;
		this.sa_ID = sa_ID;
	}

}