package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class contractData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNumber")
	private java.lang.String policyNumber;

	@org.kie.api.definition.type.Label(value = "policyDetails")
	private com.myspace.oneplatform_poc.policyDetails policyDetails;

	public contractData() {
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public com.myspace.oneplatform_poc.policyDetails getPolicyDetails() {
		return this.policyDetails;
	}

	public void setPolicyDetails(
			com.myspace.oneplatform_poc.policyDetails policyDetails) {
		this.policyDetails = policyDetails;
	}

	public contractData(java.lang.String policyNumber,
			com.myspace.oneplatform_poc.policyDetails policyDetails) {
		this.policyNumber = policyNumber;
		this.policyDetails = policyDetails;
	}

}