package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customerData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("identityNumber")
	private java.lang.String identityNumber;
	@org.kie.api.definition.type.Label("language")
	private java.lang.String language;

	public customerData() {
	}

	public java.lang.String getIdentityNumber() {
		return this.identityNumber;
	}

	public void setIdentityNumber(java.lang.String identityNumber) {
		this.identityNumber = identityNumber;
	}

	public java.lang.String getLanguage() {
		return this.language;
	}

	public void setLanguage(java.lang.String language) {
		this.language = language;
	}

	public customerData(java.lang.String identityNumber,
			java.lang.String language) {
		this.identityNumber = identityNumber;
		this.language = language;
	}

}