package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class duplicateData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "duplicateStatus")
	private java.lang.String duplicateStatus;
	@org.kie.api.definition.type.Label(value = "isDuplicate")
	private java.lang.Boolean isDuplicate;

	public duplicateData() {
	}

	public java.lang.String getDuplicateStatus() {
		return this.duplicateStatus;
	}

	public void setDuplicateStatus(java.lang.String duplicateStatus) {
		this.duplicateStatus = duplicateStatus;
	}

	public java.lang.Boolean getIsDuplicate() {
		return this.isDuplicate;
	}

	public void setIsDuplicate(java.lang.Boolean isDuplicate) {
		this.isDuplicate = isDuplicate;
	}

	public duplicateData(java.lang.String duplicateStatus,
			java.lang.Boolean isDuplicate) {
		this.duplicateStatus = duplicateStatus;
		this.isDuplicate = isDuplicate;
	}

}