package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class membership implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;

	public membership() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public membership(java.lang.String id) {
		this.id = id;
	}

}