package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class payload implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("companyData")
	private com.myspace.oneplatform_poc.companyData companyData;
	@org.kie.api.definition.type.Label("customerData")
	private com.myspace.oneplatform_poc.customerData customerData;
	@org.kie.api.definition.type.Label("policyDetails")
	private com.myspace.oneplatform_poc.policyDetails policyDetails;
	@org.kie.api.definition.type.Label("contractData")
	private com.myspace.oneplatform_poc.contractData contractData;

	public payload() {
	}

	public com.myspace.oneplatform_poc.companyData getCompanyData() {
		return this.companyData;
	}

	public void setCompanyData(
			com.myspace.oneplatform_poc.companyData companyData) {
		this.companyData = companyData;
	}

	public com.myspace.oneplatform_poc.customerData getCustomerData() {
		return this.customerData;
	}

	public void setCustomerData(
			com.myspace.oneplatform_poc.customerData customerData) {
		this.customerData = customerData;
	}

	public com.myspace.oneplatform_poc.policyDetails getPolicyDetails() {
		return this.policyDetails;
	}

	public void setPolicyDetails(
			com.myspace.oneplatform_poc.policyDetails policyDetails) {
		this.policyDetails = policyDetails;
	}

	public com.myspace.oneplatform_poc.contractData getContractData() {
		return this.contractData;
	}

	public void setContractData(
			com.myspace.oneplatform_poc.contractData contractData) {
		this.contractData = contractData;
	}

	public payload(com.myspace.oneplatform_poc.companyData companyData,
			com.myspace.oneplatform_poc.customerData customerData,
			com.myspace.oneplatform_poc.policyDetails policyDetails,
			com.myspace.oneplatform_poc.contractData contractData) {
		this.companyData = companyData;
		this.customerData = customerData;
		this.policyDetails = policyDetails;
		this.contractData = contractData;
	}

}