package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class processData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = " id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;

	public processData() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public processData(java.lang.String id, java.lang.String status,
			java.lang.String name) {
		this.id = id;
		this.status = status;
		this.name = name;
	}

}