package com.myspace.oneplatform_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class userData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("userPreference")
	private java.lang.String userPreference;

	@org.kie.api.definition.type.Label(value = "membership")
	private com.myspace.oneplatform_poc.membership membership;

	public userData() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getUserPreference() {
		return this.userPreference;
	}

	public void setUserPreference(java.lang.String userPreference) {
		this.userPreference = userPreference;
	}

	public com.myspace.oneplatform_poc.membership getMembership() {
		return this.membership;
	}

	public void setMembership(com.myspace.oneplatform_poc.membership membership) {
		this.membership = membership;
	}

	public userData(java.lang.String id, java.lang.String name,
			java.lang.String userPreference,
			com.myspace.oneplatform_poc.membership membership) {
		this.id = id;
		this.name = name;
		this.userPreference = userPreference;
		this.membership = membership;
	}

}